apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: app
spec:
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  containers:
    - name: nginx
      image: nginx:alpine
      command: []
      args: [
        "nginx", "-c", "/etc/nginx/custom/custom.conf", "-g", "daemon off;"
      ]
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/custom

