apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: app
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
          - containerPort: 8080
        command: []
        args: [
          "nginx", "-c", "/etc/nginx/custom/custom.conf", "-g", "daemon off;"
        ]
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/custom
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
          - containerPort: 80
