version: '3'
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app_development
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - 3306
  app:
    tty: true
    stdin_open: true
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0"
    volumes:
      - .:/app
      - bundle:/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_PORT: 3306
      DB_NAME: app_development
      DB_PASS: password
      DB_USER: root
      DB_HOST: db
volumes:
  bundle:
  db-data:
